const ActionTypes = {
  GETPRODUCTSUCCESS: "GETPRODUCTSUCCESS",
  GETPRODUCTERROR: "GETPRODUCTERROR",
  GET_PRODUCTDATA_LOADING: "GET_PRODUCTDATA_LOADING",
  ADD_TO_CART:"ADD_TO_CART"
};

export default ActionTypes;
